export const allTimezones = [
 // Africa
{ name: "Abidjan", zone: "Africa/Abidjan", country: "Ivory Coast" },
{ name: "Accra", zone: "Africa/Accra", country: "Ghana" },
{ name: "Addis Ababa", zone: "Africa/Addis_Ababa", country: "Ethiopia" },
{ name: "Algiers", zone: "Africa/Algiers", country: "Algeria" },
{ name: "Asmera", zone: "Africa/Asmara", country: "Eritrea" },
{ name: "Bamako", zone: "Africa/Bamako", country: "Mali" },
{ name: "Bangui", zone: "Africa/Bangui", country: "Central African Republic" },
{ name: "Banjul", zone: "Africa/Banjul", country: "Gambia" },
{ name: "Blantyre", zone: "Africa/Blantyre", country: "Malawi" },
{ name: "Brazzaville", zone: "Africa/Brazzaville", country: "Republic of the Congo" },
{ name: "Bujumbura", zone: "Africa/Bujumbura", country: "Burundi" },
{ name: "Cairo", zone: "Africa/Cairo", country: "Egypt" },
{ name: "Casablanca", zone: "Africa/Casablanca", country: "Morocco" },
{ name: "Ceuta", zone: "Africa/Ceuta", country: "Spain (Ceuta)" },
{ name: "Conakry", zone: "Africa/Conakry", country: "Guinea" },
{ name: "Dakar", zone: "Africa/Dakar", country: "Senegal" },
{ name: "Dar_es_Salaam", zone: "Africa/Dar_es_Salaam", country: "Tanzania" },
{ name: "Djibouti", zone: "Africa/Djibouti", country: "Djibouti" },
{ name: "Douala", zone: "Africa/Douala", country: "Cameroon" },
{ name: "El_Aaiun", zone: "Africa/El_Aaiun", country: "Western Sahara" },
{ name: "Freetown", zone: "Africa/Freetown", country: "Sierra Leone" },
{ name: "Gaborone", zone: "Africa/Gaborone", country: "Botswana" },
{ name: "Harare", zone: "Africa/Harare", country: "Zimbabwe" },
{ name: "Johannesburg", zone: "Africa/Johannesburg", country: "South Africa" },
{ name: "Juba", zone: "Africa/Juba", country: "South Sudan" },
{ name: "Kampala", zone: "Africa/Kampala", country: "Uganda" },
{ name: "Khartoum", zone: "Africa/Khartoum", country: "Sudan" },
{ name: "Kigali", zone: "Africa/Kigali", country: "Rwanda" },
{ name: "Kinshasa", zone: "Africa/Kinshasa", country: "Democratic Republic of the Congo" },
{ name: "Lagos", zone: "Africa/Lagos", country: "Nigeria" },
{ name: "Libreville", zone: "Africa/Libreville", country: "Gabon" },
{ name: "Lome", zone: "Africa/Lome", country: "Togo" },
{ name: "Luanda", zone: "Africa/Luanda", country: "Angola" },
{ name: "Lubumbashi", zone: "Africa/Lubumbashi", country: "Democratic Republic of the Congo" },
{ name: "Lusaka", zone: "Africa/Lusaka", country: "Zambia" },
{ name: "Malabo", zone: "Africa/Malabo", country: "Equatorial Guinea" },
{ name: "Maputo", zone: "Africa/Maputo", country: "Mozambique" },
{ name: "Maseru", zone: "Africa/Maseru", country: "Lesotho" },
{ name: "Mbabane", zone: "Africa/Mbabane", country: "Eswatini" },
{ name: "Mogadishu", zone: "Africa/Mogadishu", country: "Somalia" },
{ name: "Monrovia", zone: "Africa/Monrovia", country: "Liberia" },
{ name: "Nairobi", zone: "Africa/Nairobi", country: "Kenya" },
{ name: "Ndjamena", zone: "Africa/Ndjamena", country: "Chad" },
{ name: "Niamey", zone: "Africa/Niamey", country: "Niger" },
{ name: "Nouakchott", zone: "Africa/Nouakchott", country: "Mauritania" },
{ name: "Ouagadougou", zone: "Africa/Ouagadougou", country: "Burkina Faso" },
{ name: "Porto-Novo", zone: "Africa/Porto-Novo", country: "Benin" },
{ name: "Sao_Tome", zone: "Africa/Sao_Tome", country: "Sao Tome and Principe" },
{ name: "Tripoli", zone: "Africa/Tripoli", country: "Libya" },
{ name: "Tunis", zone: "Africa/Tunis", country: "Tunisia" },
{ name: "Windhoek", zone: "Africa/Windhoek", country: "Namibia" },

  // America
{ name: "Anchorage", zone: "America/Anchorage", country: "USA (Alaska)" },
{ name: "Araguaina", zone: "America/Araguaina", country: "Brazil" },
{ name: "Buenos Aires", zone: "America/Argentina/Buenos_Aires", country: "Argentina" },
{ name: "Catamarca", zone: "America/Argentina/Catamarca", country: "Argentina" },
{ name: "Cordoba", zone: "America/Argentina/Cordoba", country: "Argentina" },
{ name: "Jujuy", zone: "America/Argentina/Jujuy", country: "Argentina" },
{ name: "La Rioja", zone: "America/Argentina/La_Rioja", country: "Argentina" },
{ name: "Mendoza", zone: "America/Argentina/Mendoza", country: "Argentina" },
{ name: "Rio Gallegos", zone: "America/Argentina/Rio_Gallegos", country: "Argentina" },
{ name: "Salta", zone: "America/Argentina/Salta", country: "Argentina" },
{ name: "San Juan", zone: "America/Argentina/San_Juan", country: "Argentina" },
{ name: "San Luis", zone: "America/Argentina/San_Luis", country: "Argentina" },
{ name: "Tucuman", zone: "America/Argentina/Tucuman", country: "Argentina" },
{ name: "Ushuaia", zone: "America/Argentina/Ushuaia", country: "Argentina" },
{ name: "Bogota", zone: "America/Bogota", country: "Colombia" },
{ name: "Caracas", zone: "America/Caracas", country: "Venezuela" },
{ name: "Chicago", zone: "America/Chicago", country: "USA (Central)" },
{ name: "Costa Rica", zone: "America/Costa_Rica", country: "Costa Rica" },
{ name: "Denver", zone: "America/Denver", country: "USA (Mountain)" },
{ name: "Detroit", zone: "America/Detroit", country: "USA (Eastern)" },
{ name: "Edmonton", zone: "America/Edmonton", country: "Canada (Alberta)" },
{ name: "Guayaquil", zone: "America/Guayaquil", country: "Ecuador" },
{ name: "Los Angeles", zone: "America/Los_Angeles", country: "USA (Pacific)" },
{ name: "Mexico City", zone: "America/Mexico_City", country: "Mexico" },
{ name: "Monterrey", zone: "America/Monterrey", country: "Mexico" },
{ name: "New York", zone: "America/New_York", country: "USA (Eastern)" },
{ name: "Panama", zone: "America/Panama", country: "Panama" },
{ name: "Phoenix", zone: "America/Phoenix", country: "USA (Arizona)" },
{ name: "Port-au-Prince", zone: "America/Port-au-Prince", country: "Haiti" },
{ name: "Santiago", zone: "America/Santiago", country: "Chile" },
{ name: "Sao Paulo", zone: "America/Sao_Paulo", country: "Brazil" },
{ name: "Toronto", zone: "America/Toronto", country: "Canada" },
{ name: "Vancouver", zone: "America/Vancouver", country: "Canada" },
{ name: "Winnipeg", zone: "America/Winnipeg", country: "Canada" },
{ name: "Montevideo", zone: "America/Montevideo", country: "Uruguay" },
{ name: "La Paz", zone: "America/La_Paz", country: "Bolivia" },
{ name: "Havana", zone: "America/Havana", country: "Cuba" },
{ name: "Puerto Rico", zone: "America/Puerto_Rico", country: "Puerto Rico" },


  // Asia
{ name: "Aden", zone: "Asia/Aden", country: "Yemen" },
{ name: "Almaty", zone: "Asia/Almaty", country: "Kazakhstan" },
{ name: "Amman", zone: "Asia/Amman", country: "Jordan" },
{ name: "Baghdad", zone: "Asia/Baghdad", country: "Iraq" },
{ name: "Baku", zone: "Asia/Baku", country: "Azerbaijan" },
{ name: "Bangkok", zone: "Asia/Bangkok", country: "Thailand" },
{ name: "Beirut", zone: "Asia/Beirut", country: "Lebanon" },
{ name: "Colombo", zone: "Asia/Colombo", country: "Sri Lanka" },
{ name: "Damascus", zone: "Asia/Damascus", country: "Syria" },
{ name: "Dhaka", zone: "Asia/Dhaka", country: "Bangladesh" },
{ name: "Dubai", zone: "Asia/Dubai", country: "UAE" },
{ name: "Dushanbe", zone: "Asia/Dushanbe", country: "Tajikistan" },
{ name: "Hong Kong", zone: "Asia/Hong_Kong", country: "Hong Kong" },
{ name: "Jakarta", zone: "Asia/Jakarta", country: "Indonesia" },
{ name: "Jerusalem", zone: "Asia/Jerusalem", country: "Israel" },
{ name: "Kabul", zone: "Asia/Kabul", country: "Afghanistan" },
{ name: "Karachi", zone: "Asia/Karachi", country: "Pakistan" },
{ name: "Kathmandu", zone: "Asia/Kathmandu", country: "Nepal" },
{ name: "Kolkata", zone: "Asia/Kolkata", country: "India" },
{ name: "Krasnoyarsk", zone: "Asia/Krasnoyarsk", country: "Russia" },
{ name: "Kuala Lumpur", zone: "Asia/Kuala_Lumpur", country: "Malaysia" },
{ name: "Kuwait", zone: "Asia/Kuwait", country: "Kuwait" },
{ name: "Macau", zone: "Asia/Macau", country: "Macau" },
{ name: "Magadan", zone: "Asia/Magadan", country: "Russia" },
{ name: "Manila", zone: "Asia/Manila", country: "Philippines" },
{ name: "Muscat", zone: "Asia/Muscat", country: "Oman" },
{ name: "Novokuznetsk", zone: "Asia/Novokuznetsk", country: "Russia" },
{ name: "Novosibirsk", zone: "Asia/Novosibirsk", country: "Russia" },
{ name: "Riyadh", zone: "Asia/Riyadh", country: "Saudi Arabia" },
{ name: "Samarkand", zone: "Asia/Samarkand", country: "Uzbekistan" },
{ name: "Seoul", zone: "Asia/Seoul", country: "South Korea" },
{ name: "Shanghai", zone: "Asia/Shanghai", country: "China" },
{ name: "Singapore", zone: "Asia/Singapore", country: "Singapore" },
{ name: "Taipei", zone: "Asia/Taipei", country: "Taiwan" },
{ name: "Tashkent", zone: "Asia/Tashkent", country: "Uzbekistan" },
{ name: "Tehran", zone: "Asia/Tehran", country: "Iran" },
{ name: "Tokyo", zone: "Asia/Tokyo", country: "Japan" },
{ name: "Ulaanbaatar", zone: "Asia/Ulaanbaatar", country: "Mongolia" },
{ name: "Vladivostok", zone: "Asia/Vladivostok", country: "Russia" },
{ name: "Yakutsk", zone: "Asia/Yakutsk", country: "Russia" },
{ name: "Yangon", zone: "Asia/Yangon", country: "Myanmar" },
{ name: "Yekaterinburg", zone: "Asia/Yekaterinburg", country: "Russia" },


  // Australia & Pacific
{ name: "Adelaide", zone: "Australia/Adelaide", country: "Australia" },
{ name: "Brisbane", zone: "Australia/Brisbane", country: "Australia" },
{ name: "Darwin", zone: "Australia/Darwin", country: "Australia" },
{ name: "Hobart", zone: "Australia/Hobart", country: "Australia" },
{ name: "Melbourne", zone: "Australia/Melbourne", country: "Australia" },
{ name: "Perth", zone: "Australia/Perth", country: "Australia" },
{ name: "Sydney", zone: "Australia/Sydney", country: "Australia" },
{ name: "Auckland", zone: "Pacific/Auckland", country: "New Zealand" },
{ name: "Chatham", zone: "Pacific/Chatham", country: "New Zealand" },
{ name: "Fiji", zone: "Pacific/Fiji", country: "Fiji" },
{ name: "Guam", zone: "Pacific/Guam", country: "Guam" },
{ name: "Honolulu", zone: "Pacific/Honolulu", country: "USA (Hawaii)" },
{ name: "Kiritimati", zone: "Pacific/Kiritimati", country: "Kiribati" },
{ name: "Majuro", zone: "Pacific/Majuro", country: "Marshall Islands" },
{ name: "Pago Pago", zone: "Pacific/Pago_Pago", country: "American Samoa" },
{ name: "Port Moresby", zone: "Pacific/Port_Moresby", country: "Papua New Guinea" },
{ name: "Rarotonga", zone: "Pacific/Rarotonga", country: "Cook Islands" },
{ name: "Tahiti", zone: "Pacific/Tahiti", country: "French Polynesia" },
{ name: "Tarawa", zone: "Pacific/Tarawa", country: "Kiribati" },
{ name: "Tongatapu", zone: "Pacific/Tongatapu", country: "Tonga" },
{ name: "Wake", zone: "Pacific/Wake", country: "USA (Wake Island)" },
{ name: "Wallis", zone: "Pacific/Wallis", country: "Wallis and Futuna" },


  // Europe
{ name: "Amsterdam", zone: "Europe/Amsterdam", country: "Netherlands" },
{ name: "Andorra", zone: "Europe/Andorra", country: "Andorra" },
{ name: "Athens", zone: "Europe/Athens", country: "Greece" },
{ name: "Belgrade", zone: "Europe/Belgrade", country: "Serbia" },
{ name: "Berlin", zone: "Europe/Berlin", country: "Germany" },
{ name: "Bratislava", zone: "Europe/Bratislava", country: "Slovakia" },
{ name: "Brussels", zone: "Europe/Brussels", country: "Belgium" },
{ name: "Bucharest", zone: "Europe/Bucharest", country: "Romania" },
{ name: "Budapest", zone: "Europe/Budapest", country: "Hungary" },
{ name: "Chisinau", zone: "Europe/Chisinau", country: "Moldova" },
{ name: "Copenhagen", zone: "Europe/Copenhagen", country: "Denmark" },
{ name: "Dublin", zone: "Europe/Dublin", country: "Ireland" },
{ name: "Gibraltar", zone: "Europe/Gibraltar", country: "Gibraltar" },
{ name: "Helsinki", zone: "Europe/Helsinki", country: "Finland" },
{ name: "Istanbul", zone: "Europe/Istanbul", country: "Turkey" },
{ name: "Kaliningrad", zone: "Europe/Kaliningrad", country: "Russia" },
{ name: "Kiev", zone: "Europe/Kiev", country: "Ukraine" },
{ name: "Lisbon", zone: "Europe/Lisbon", country: "Portugal" },
{ name: "Ljubljana", zone: "Europe/Ljubljana", country: "Slovenia" },
{ name: "London", zone: "Europe/London", country: "United Kingdom" },
{ name: "Luxembourg", zone: "Europe/Luxembourg", country: "Luxembourg" },
{ name: "Madrid", zone: "Europe/Madrid", country: "Spain" },
{ name: "Malta", zone: "Europe/Malta", country: "Malta" },
{ name: "Minsk", zone: "Europe/Minsk", country: "Belarus" },
{ name: "Monaco", zone: "Europe/Monaco", country: "Monaco" },
{ name: "Moscow", zone: "Europe/Moscow", country: "Russia" },
{ name: "Oslo", zone: "Europe/Oslo", country: "Norway" },
{ name: "Paris", zone: "Europe/Paris", country: "France" },
{ name: "Podgorica", zone: "Europe/Podgorica", country: "Montenegro" },
{ name: "Prague", zone: "Europe/Prague", country: "Czech Republic" },
{ name: "Riga", zone: "Europe/Riga", country: "Latvia" },
{ name: "Rome", zone: "Europe/Rome", country: "Italy" },
{ name: "San Marino", zone: "Europe/San_Marino", country: "San Marino" },
{ name: "Sarajevo", zone: "Europe/Sarajevo", country: "Bosnia and Herzegovina" },
{ name: "Simferopol", zone: "Europe/Simferopol", country: "Russia/Ukraine" },
{ name: "Skopje", zone: "Europe/Skopje", country: "North Macedonia" },
{ name: "Sofia", zone: "Europe/Sofia", country: "Bulgaria" },
{ name: "Stockholm", zone: "Europe/Stockholm", country: "Sweden" },
{ name: "Tallinn", zone: "Europe/Tallinn", country: "Estonia" },
{ name: "Tirane", zone: "Europe/Tirane", country: "Albania" },
{ name: "Vaduz", zone: "Europe/Vaduz", country: "Liechtenstein" },
{ name: "Valletta", zone: "Europe/Valletta", country: "Malta" },
{ name: "Vatican", zone: "Europe/Vatican", country: "Vatican City" },
{ name: "Vienna", zone: "Europe/Vienna", country: "Austria" },
{ name: "Vilnius", zone: "Europe/Vilnius", country: "Lithuania" },
{ name: "Warsaw", zone: "Europe/Warsaw", country: "Poland" },
{ name: "Zagreb", zone: "Europe/Zagreb", country: "Croatia" },
{ name: "Zurich", zone: "Europe/Zurich", country: "Switzerland" },


// Antarctica
{ name: "Casey", zone: "Antarctica/Casey", country: "Australia (Antarctica)" },
{ name: "Davis", zone: "Antarctica/Davis", country: "Australia (Antarctica)" },
{ name: "DumontDUrville", zone: "Antarctica/DumontDUrville", country: "France (Antarctica)" },
{ name: "Macquarie", zone: "Antarctica/Macquarie", country: "Australia (Antarctica)" },
{ name: "Mawson", zone: "Antarctica/Mawson", country: "Australia (Antarctica)" },
{ name: "McMurdo", zone: "Antarctica/McMurdo", country: "New Zealand (Antarctica)" },
{ name: "Palmer", zone: "Antarctica/Palmer", country: "USA (Antarctica)" },
{ name: "Rothera", zone: "Antarctica/Rothera", country: "UK (Antarctica)" },
{ name: "South_Pole", zone: "Antarctica/South_Pole", country: "USA (Antarctica)" },
{ name: "Syowa", zone: "Antarctica/Syowa", country: "Japan (Antarctica)" },
{ name: "Troll", zone: "Antarctica/Troll", country: "Norway (Antarctica)" },
{ name: "Vostok", zone: "Antarctica/Vostok", country: "Russia (Antarctica)" },

// Atlantic
{ name: "Azores", zone: "Atlantic/Azores", country: "Portugal" },
{ name: "Bermuda", zone: "Atlantic/Bermuda", country: "Bermuda" },
{ name: "Canary", zone: "Atlantic/Canary", country: "Spain" },
{ name: "Cape Verde", zone: "Atlantic/Cape_Verde", country: "Cape Verde" },
{ name: "Faroe", zone: "Atlantic/Faroe", country: "Faroe Islands" },
{ name: "Madeira", zone: "Atlantic/Madeira", country: "Portugal" },
{ name: "Reykjavik", zone: "Atlantic/Reykjavik", country: "Iceland" },
{ name: "South_Georgia", zone: "Atlantic/South_Georgia", country: "South Georgia and the South Sandwich Islands" },
{ name: "St_Helena", zone: "Atlantic/St_Helena", country: "Saint Helena" },

// Arctic
{ name: "Longyearbyen", zone: "Arctic/Longyearbyen", country: "Svalbard and Jan Mayen" },

// Misc/Other
{ name: "UTC", zone: "Etc/UTC", country: "Universal Coordinated Time" },
{ name: "GMT", zone: "Etc/GMT", country: "Greenwich Mean Time" },
{ name: "GMT+0", zone: "Etc/GMT+0", country: "GMT+0" },
{ name: "GMT+1", zone: "Etc/GMT+1", country: "GMT+1" },
{ name: "GMT+2", zone: "Etc/GMT+2", country: "GMT+2" },
{ name: "GMT+3", zone: "Etc/GMT+3", country: "GMT+3" },
{ name: "GMT+4", zone: "Etc/GMT+4", country: "GMT+4" },
{ name: "GMT+5", zone: "Etc/GMT+5", country: "GMT+5" },
{ name: "GMT+6", zone: "Etc/GMT+6", country: "GMT+6" },
{ name: "GMT+7", zone: "Etc/GMT+7", country: "GMT+7" },
{ name: "GMT+8", zone: "Etc/GMT+8", country: "GMT+8" },
{ name: "GMT+9", zone: "Etc/GMT+9", country: "GMT+9" },
{ name: "GMT+10", zone: "Etc/GMT+10", country: "GMT+10" },
{ name: "GMT+11", zone: "Etc/GMT+11", country: "GMT+11" },
{ name: "GMT+12", zone: "Etc/GMT+12", country: "GMT+12" },
{ name: "GMT-1", zone: "Etc/GMT-1", country: "GMT-1" },
{ name: "GMT-2", zone: "Etc/GMT-2", country: "GMT-2" },
{ name: "GMT-3", zone: "Etc/GMT-3", country: "GMT-3" },
{ name: "GMT-4", zone: "Etc/GMT-4", country: "GMT-4" },
{ name: "GMT-5", zone: "Etc/GMT-5", country: "GMT-5" },
{ name: "GMT-6", zone: "Etc/GMT-6", country: "GMT-6" },
{ name: "GMT-7", zone: "Etc/GMT-7", country: "GMT-7" },
{ name: "GMT-8", zone: "Etc/GMT-8", country: "GMT-8" },
{ name: "GMT-9", zone: "Etc/GMT-9", country: "GMT-9" },
{ name: "GMT-10", zone: "Etc/GMT-10", country: "GMT-10" },
{ name: "GMT-11", zone: "Etc/GMT-11", country: "GMT-11" },
{ name: "GMT-12", zone: "Etc/GMT-12", country: "GMT-12" },


]
