export interface Tool {
  slug: string
  title: string
  description: string
  category: "calculator" | "converter" | "generator" | "text-tool" | "utility"
  icon: string
  keywords: string[]
  longDescription: string
}

export const toolsData: Tool[] = [
  // Calculators
  {
    slug: "age-calculator",
    title: "Age Calculator",
    description: "Calculate your exact age in years, months, and days",
    category: "calculator",
    icon: "Calendar",
    keywords: [
      "age calculator",
      "calculate age",
      "age in days",
      "age in months",
      "date of birth calculator",
      "how old am i",
      "age difference calculator",
      "birthday calculator",
    ],
    longDescription:
      "Calculate your exact age with our free online age calculator. Find out your age in years, months, days, hours, and minutes. Perfect for calculating age differences, planning birthdays, or determining eligibility for age-restricted activities.",
  },
  {
    slug: "bmi-calculator",
    title: "BMI Calculator",
    description: "Calculate your Body Mass Index and health category",
    category: "calculator",
    icon: "Activity",
    keywords: [
      "bmi calculator",
      "body mass index",
      "weight calculator",
      "health calculator",
      "obesity calculator",
      "ideal weight",
      "healthy weight calculator",
      "fitness calculator",
    ],
    longDescription:
      "Calculate your Body Mass Index (BMI) instantly with our free BMI calculator. Determine if you're underweight, normal weight, overweight, or obese. Get personalized health insights based on your height and weight measurements.",
  },
  {
    slug: "loan-calculator",
    title: "Loan Calculator",
    description: "Calculate monthly payments and total interest",
    category: "calculator",
    icon: "DollarSign",
    keywords: [
      "loan calculator",
      "mortgage calculator",
      "monthly payment calculator",
      "interest calculator",
      "car loan calculator",
      "personal loan calculator",
      "amortization calculator",
      "emi calculator",
    ],
    longDescription:
      "Calculate your loan payments with our comprehensive loan calculator. Determine monthly payments, total interest, and amortization schedules for mortgages, car loans, personal loans, and more. Plan your finances with accurate loan calculations.",
  },
  {
    slug: "discount-calculator",
    title: "Discount Calculator",
    description: "Calculate discounts and final prices",
    category: "calculator",
    icon: "Percent",
    keywords: [
      "discount calculator",
      "percentage off calculator",
      "sale price calculator",
      "savings calculator",
      "price reduction calculator",
      "markdown calculator",
      "clearance calculator",
    ],
    longDescription:
      "Calculate discounts and sale prices instantly. Find out how much you save with percentage discounts, determine final prices after markdowns, and compare deals. Perfect for shopping, retail, and business pricing.",
  },
  {
    slug: "tip-calculator",
    title: "Tip Calculator",
    description: "Calculate tips and split bills easily",
    category: "calculator",
    icon: "Receipt",
    keywords: [
      "tip calculator",
      "gratuity calculator",
      "bill splitter",
      "restaurant tip calculator",
      "service charge calculator",
      "split bill calculator",
      "tipping calculator",
    ],
    longDescription:
      "Calculate tips and split bills effortlessly with our tip calculator. Determine appropriate gratuity amounts, split bills among friends, and calculate per-person costs. Perfect for restaurants, bars, and group dining.",
  },
  {
    slug: "percentage-calculator",
    title: "Percentage Calculator",
    description: "Calculate percentages, increases, and decreases",
    category: "calculator",
    icon: "Percent",
    keywords: [
      "percentage calculator",
      "percent calculator",
      "percentage increase calculator",
      "percentage decrease calculator",
      "percentage change calculator",
      "percentage difference calculator",
      "calculate percentage",
    ],
    longDescription:
      "Calculate percentages, percentage increases, decreases, and differences. Perfect for business, finance, statistics, and everyday calculations. Find what percentage one number is of another, calculate percentage changes, and more.",
  },
  {
    slug: "fraction-calculator",
    title: "Fraction Calculator",
    description: "Add, subtract, multiply, and divide fractions",
    category: "calculator",
    icon: "Divide",
    keywords: [
      "fraction calculator",
      "fraction addition",
      "fraction subtraction",
      "fraction multiplication",
      "fraction division",
      "simplify fractions",
      "fraction converter",
    ],
    longDescription:
      "Calculate fractions with ease. Add, subtract, multiply, and divide fractions. Simplify fractions and convert between fractions and decimals. Perfect for students, teachers, and anyone working with fractions.",
  },
  {
    slug: "mortgage-calculator",
    title: "Mortgage Calculator",
    description: "Calculate monthly mortgage payments and amortization",
    category: "calculator",
    icon: "Home",
    keywords: [
      "mortgage calculator",
      "home loan calculator",
      "mortgage payment calculator",
      "house payment calculator",
      "mortgage amortization",
      "home affordability calculator",
      "mortgage estimator",
    ],
    longDescription:
      "Calculate monthly mortgage payments, total interest, and amortization schedules. Perfect for home buyers planning their finances. Includes property tax and insurance estimates for accurate monthly payment calculations.",
  },
  {
    slug: "investment-calculator",
    title: "Investment Calculator",
    description: "Calculate investment returns and growth",
    category: "calculator",
    icon: "TrendingUp",
    keywords: [
      "investment calculator",
      "roi calculator",
      "return on investment",
      "investment return calculator",
      "portfolio calculator",
      "stock calculator",
      "investment growth calculator",
    ],
    longDescription:
      "Calculate investment returns, compound growth, and ROI. Perfect for investors planning their portfolio strategy. Includes options for regular contributions and different compounding frequencies.",
  },
  {
    slug: "compound-interest-calculator",
    title: "Compound Interest Calculator",
    description: "Calculate compound interest and investment growth",
    category: "calculator",
    icon: "PiggyBank",
    keywords: [
      "compound interest calculator",
      "compound interest",
      "interest calculator",
      "savings calculator",
      "compound growth calculator",
      "investment compound calculator",
    ],
    longDescription:
      "Calculate compound interest on savings and investments. See how your money grows over time with different interest rates and compounding frequencies. Perfect for retirement planning and savings goals.",
  },

  // Converters
  {
    slug: "unit-converter",
    title: "Unit Converter",
    description: "Convert between different units of measurement",
    category: "converter",
    icon: "ArrowLeftRight",
    keywords: [
      "unit converter",
      "measurement converter",
      "length converter",
      "weight converter",
      "volume converter",
      "metric converter",
      "imperial converter",
      "conversion calculator",
    ],
    longDescription:
      "Convert between different units of measurement instantly. Support for length, weight, volume, area, and more. Convert metric to imperial, imperial to metric, and between various measurement systems with ease.",
  },
  {
    slug: "currency-converter",
    title: "Currency Converter",
    description: "Convert between world currencies with live rates",
    category: "converter",
    icon: "Coins",
    keywords: [
      "currency converter",
      "exchange rate calculator",
      "money converter",
      "forex converter",
      "foreign exchange calculator",
      "usd to eur",
      "currency exchange",
      "live exchange rates",
    ],
    longDescription:
      "Convert between world currencies with real-time exchange rates. Support for USD, EUR, GBP, JPY, and 150+ currencies. Get accurate currency conversions for travel, business, and international transactions.",
  },
  {
    slug: "temperature-converter",
    title: "Temperature Converter",
    description: "Convert between Celsius, Fahrenheit, and Kelvin",
    category: "converter",
    icon: "Thermometer",
    keywords: [
      "temperature converter",
      "celsius to fahrenheit",
      "fahrenheit to celsius",
      "kelvin converter",
      "temperature calculator",
      "c to f converter",
      "f to c converter",
    ],
    longDescription:
      "Convert temperatures between Celsius, Fahrenheit, and Kelvin instantly. Perfect for cooking, weather, science, and international travel. Get accurate temperature conversions with our easy-to-use converter.",
  },
  {
    slug: "binary-converter",
    title: "Binary Converter",
    description: "Convert between binary, decimal, and hexadecimal",
    category: "converter",
    icon: "Binary",
    keywords: [
      "binary converter",
      "decimal to binary",
      "hex converter",
      "hexadecimal converter",
      "number system converter",
      "base converter",
      "binary calculator",
    ],
    longDescription:
      "Convert between binary, decimal, and hexadecimal number systems. Perfect for programmers, students, and computer science enthusiasts. Fast and accurate number base conversions.",
  },
  {
    slug: "time-zone-converter",
    title: "Time Zone Converter",
    description: "Convert time between different time zones",
    category: "converter",
    icon: "Clock",
    keywords: [
      "time zone converter",
      "timezone calculator",
      "world clock",
      "time difference calculator",
      "gmt converter",
      "utc converter",
      "international time converter",
    ],
    longDescription:
      "Convert time between different time zones worldwide. Perfect for scheduling international meetings, planning travel, and coordinating with global teams. Support for all major time zones and daylight saving time.",
  },
  {
    slug: "rgb-hex-converter",
    title: "RGB to HEX Converter",
    description: "Convert between RGB and HEX color codes",
    category: "converter",
    icon: "Palette",
    keywords: [
      "rgb to hex",
      "hex to rgb",
      "color converter",
      "rgb converter",
      "hex converter",
      "color code converter",
      "css color converter",
    ],
    longDescription:
      "Convert between RGB and HEX color codes instantly. Perfect for web designers and developers. Get accurate color conversions for CSS, HTML, and design projects.",
  },
  {
    slug: "unix-timestamp",
    title: "Unix Timestamp Converter",
    description: "Convert Unix timestamps to dates and vice versa",
    category: "converter",
    icon: "Clock",
    keywords: [
      "unix timestamp converter",
      "epoch converter",
      "timestamp to date",
      "date to timestamp",
      "unix time converter",
      "epoch time converter",
      "timestamp calculator",
    ],
    longDescription:
      "Convert Unix timestamps to human-readable dates and vice versa. Perfect for developers, system administrators, and anyone working with timestamps. Support for milliseconds and seconds.",
  },
  {
    slug: "base-converter",
    title: "Base Converter",
    description: "Convert numbers between any base (2-36)",
    category: "converter",
    icon: "Binary",
    keywords: [
      "base converter",
      "number base converter",
      "radix converter",
      "binary to decimal",
      "octal converter",
      "hexadecimal converter",
      "base conversion",
    ],
    longDescription:
      "Convert numbers between any base from 2 to 36. Support for binary, octal, decimal, hexadecimal, and custom bases. Perfect for programmers and computer science students.",
  },
  
  {
    slug: "image-converter",
    title: "Image Format Converter",
    description: "Convert images between different formats",
    category: "converter",
    icon: "Image",
    keywords: [
      "image converter",
      "convert image format",
      "jpg to png",
      "png to jpg",
      "webp converter",
      "image format changer",
      "convert photo format",
    ],
    longDescription:
      "Convert images between JPG, PNG, WebP, and other formats. Perfect for web optimization, compatibility, and file size reduction. Fast and secure image format conversion.",
  },
  {
    slug: "pdf-to-image",
    title: "PDF to Image Converter",
    description: "Convert PDF pages to JPG or PNG images",
    category: "converter",
    icon: "FileImage",
    keywords: [
      "pdf to image",
      "pdf to jpg",
      "pdf to png",
      "convert pdf to image",
      "pdf to picture",
      "pdf page to image",
      "extract images from pdf",
    ],
    longDescription:
      "Convert PDF pages to high-quality JPG or PNG images. Extract all pages or specific pages from PDF documents. Perfect for sharing, presentations, and image editing. Fast and secure PDF to image conversion.",
  },
  {
    slug: "base64-encoder",
    title: "Base64 Encoder/Decoder",
    description: "Encode and decode Base64 strings",
    category: "converter",
    icon: "Binary",
    keywords: [
      "base64 encoder",
      "base64 decoder",
      "base64 converter",
      "encode base64",
      "decode base64",
      "base64 tool",
      "base64 online",
    ],
    longDescription:
      "Encode and decode Base64 strings. Perfect for developers working with data encoding, API requests, and file transfers. Support for text and file encoding.",
  },
  {
    slug: "url-encoder",
    title: "URL Encoder/Decoder",
    description: "Encode and decode URL strings",
    category: "converter",
    icon: "Link",
    keywords: [
      "url encoder",
      "url decoder",
      "url encode",
      "url decode",
      "percent encoding",
      "uri encoder",
      "url escape",
    ],
    longDescription:
      "Encode and decode URL strings for safe transmission. Perfect for developers working with APIs, query parameters, and web applications. Handle special characters in URLs correctly.",
  },
  {
    slug: "csv-to-json",
    title: "CSV to JSON Converter",
    description: "Convert CSV data to JSON format",
    category: "converter",
    icon: "FileJson",
    keywords: [
      "csv to json",
      "json to csv",
      "csv converter",
      "json converter",
      "data converter",
      "csv parser",
      "json parser",
    ],
    longDescription:
      "Convert CSV data to JSON format and vice versa. Perfect for developers, data analysts, and anyone working with data formats. Fast and accurate data conversion.",
  },

  // Generators
  {
    slug: "password-generator",
    title: "Password Generator",
    description: "Generate secure random passwords",
    category: "generator",
    icon: "Key",
    keywords: [
      "password generator",
      "random password",
      "secure password generator",
      "strong password creator",
      "password maker",
      "passphrase generator",
      "random password generator",
    ],
    longDescription:
      "Generate strong, secure random passwords instantly. Customize length, include special characters, numbers, and uppercase letters. Create unbreakable passwords for maximum security online.",
  },
  {
    slug: "lorem-ipsum",
    title: "Lorem Ipsum Generator",
    description: "Generate placeholder text for designs",
    category: "generator",
    icon: "FileText",
    keywords: [
      "lorem ipsum generator",
      "placeholder text",
      "dummy text generator",
      "filler text",
      "lipsum generator",
      "sample text",
      "mock text generator",
    ],
    longDescription:
      "Generate Lorem Ipsum placeholder text for your designs and mockups. Customize paragraph count, word count, and format. Perfect for designers, developers, and content creators.",
  },
  {
    slug: "random-number",
    title: "Random Number Generator",
    description: "Generate random numbers in any range",
    category: "generator",
    icon: "Dices",
    keywords: [
      "random number generator",
      "random number picker",
      "number generator",
      "random integer",
      "lottery number generator",
      "dice roller",
      "rng",
    ],
    longDescription:
      "Generate random numbers within any range. Perfect for games, lotteries, statistical sampling, and decision making. Customize minimum and maximum values for precise random number generation.",
  },
  {
    slug: "color-picker",
    title: "Color Picker",
    description: "Pick colors and get HEX, RGB, HSL values",
    category: "generator",
    icon: "Palette",
    keywords: [
      "color picker",
      "hex color picker",
      "rgb color picker",
      "color selector",
      "color code generator",
      "color palette generator",
      "html color picker",
    ],
    longDescription:
      "Pick colors and get HEX, RGB, and HSL values instantly. Perfect for web designers, graphic designers, and developers. Create color palettes and find the perfect colors for your projects.",
  },
  {
    slug: "uuid-generator",
    title: "UUID Generator",
    description: "Generate unique identifiers (UUIDs)",
    category: "generator",
    icon: "Hash",
    keywords: [
      "uuid generator",
      "guid generator",
      "unique id generator",
      "random uuid",
      "uuid v4 generator",
      "identifier generator",
      "unique identifier",
    ],
    longDescription:
      "Generate universally unique identifiers (UUIDs) instantly. Perfect for developers, database administrators, and software engineers. Create UUID v4 identifiers for databases, APIs, and applications.",
  },
  {
    slug: "hash-generator",
    title: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256 hashes",
    category: "generator",
    icon: "Hash",
    keywords: [
      "hash generator",
      "md5 generator",
      "sha1 generator",
      "sha256 generator",
      "checksum calculator",
      "hash calculator",
      "crypto hash",
    ],
    longDescription:
      "Generate cryptographic hashes (MD5, SHA-1, SHA-256) for text and files. Perfect for verifying file integrity, password hashing, and security applications. Fast and secure hash generation.",
  },
  {
    slug: "qr-code-generator",
    title: "QR Code Generator",
    description: "Generate QR codes for URLs, text, and more",
    category: "generator",
    icon: "QrCode",
    keywords: [
      "qr code generator",
      "create qr code",
      "qr code maker",
      "generate qr code",
      "free qr code",
      "qr code creator",
      "custom qr code",
      "qr code online",
    ],
    longDescription:
      "Generate custom QR codes instantly for URLs, text, contact information, and more. Download high-quality QR codes in PNG format. Perfect for marketing, business cards, product packaging, and event management.",
  },
  {
    slug: "barcode-generator",
    title: "Barcode Generator",
    description: "Generate barcodes in multiple formats",
    category: "generator",
    icon: "Barcode",
    keywords: [
      "barcode generator",
      "create barcode",
      "barcode maker",
      "generate barcode",
      "free barcode",
      "barcode creator",
      "ean barcode",
      "upc barcode",
    ],
    longDescription:
      "Generate barcodes in multiple formats including EAN-13, UPC-A, Code 128, and more. Download high-quality barcodes for products, inventory management, and retail applications. Free and easy to use.",
  },
  {
    slug: "meta-tag-generator",
    title: "Meta Tag Generator",
    description: "Generate SEO meta tags for websites",
    category: "generator",
    icon: "Tags",
    keywords: [
      "meta tag generator",
      "seo meta tags",
      "og tags generator",
      "twitter card generator",
      "meta tags creator",
      "seo tags generator",
      "html meta tags",
    ],
    longDescription:
      "Generate SEO-optimized meta tags for your website. Create Open Graph tags for social media, Twitter Cards, and standard meta tags. Perfect for improving search engine visibility and social sharing.",
  },

  // Text Tools
  {
    slug: "word-counter",
    title: "Word Counter",
    description: "Count words, characters, and sentences",
    category: "text-tool",
    icon: "Type",
    keywords: [
      "word counter",
      "character counter",
      "word count tool",
      "text counter",
      "sentence counter",
      "paragraph counter",
      "letter counter",
    ],
    longDescription:
      "Count words, characters, sentences, and paragraphs in your text. Perfect for writers, students, and content creators. Track word count for essays, articles, social media posts, and more.",
  },
  {
    slug: "text-case-converter",
    title: "Text Case Converter",
    description: "Convert text to uppercase, lowercase, or title case",
    category: "text-tool",
    icon: "CaseSensitive",
    keywords: [
      "text case converter",
      "uppercase converter",
      "lowercase converter",
      "title case converter",
      "sentence case converter",
      "capitalize text",
      "text transformer",
    ],
    longDescription:
      "Convert text between uppercase, lowercase, title case, and sentence case. Perfect for formatting text, fixing caps lock mistakes, and standardizing text formatting. Fast and easy text case conversion.",
  },
  {
    slug: "text-cleaner",
    title: "Text Cleaner",
    description: "Remove extra spaces and clean up text",
    category: "text-tool",
    icon: "Eraser",
    keywords: [
      "text cleaner",
      "remove extra spaces",
      "clean text",
      "text formatter",
      "whitespace remover",
      "text trimmer",
      "text sanitizer",
    ],
    longDescription:
      "Clean up text by removing extra spaces, line breaks, and special characters. Perfect for cleaning copied text, formatting documents, and preparing text for processing. Fast and efficient text cleaning.",
  },
  {
    slug: "json-formatter",
    title: "JSON Formatter",
    description: "Format and validate JSON data",
    category: "text-tool",
    icon: "Braces",
    keywords: [
      "json formatter",
      "json validator",
      "json beautifier",
      "json pretty print",
      "json parser",
      "json viewer",
      "format json",
    ],
    longDescription:
      "Format, validate, and beautify JSON data. Perfect for developers working with APIs, configuration files, and data structures. Validate JSON syntax and make it human-readable with proper indentation.",
  },
  {
    slug: "markdown-converter",
    title: "Markdown to HTML",
    description: "Convert Markdown to HTML",
    category: "text-tool",
    icon: "Code",
    keywords: [
      "markdown converter",
      "markdown to html",
      "markdown parser",
      "md to html",
      "markdown preview",
      "markdown editor",
      "markdown formatter",
    ],
    longDescription:
      "Convert Markdown to HTML instantly. Perfect for bloggers, developers, and content creators. Preview your Markdown content and generate clean HTML code for websites and applications.",
  },
  {
    slug: "text-diff",
    title: "Text Diff Checker",
    description: "Compare two texts and find differences",
    category: "text-tool",
    icon: "FileSearch",
    keywords: [
      "text diff",
      "text compare",
      "diff checker",
      "text comparison",
      "compare text",
      "difference checker",
      "text analyzer",
    ],
    longDescription:
      "Compare two texts and highlight differences. Perfect for developers, writers, and editors. Find changes between versions, compare documents, and track text modifications.",
  },
  {
    slug: "duplicate-remover",
    title: "Duplicate Line Remover",
    description: "Remove duplicate lines from text",
    category: "text-tool",
    icon: "Copy",
    keywords: [
      "duplicate remover",
      "remove duplicates",
      "duplicate line remover",
      "unique lines",
      "text deduplication",
      "remove duplicate text",
    ],
    longDescription:
      "Remove duplicate lines from text instantly. Perfect for cleaning data, processing lists, and removing redundant content. Fast and efficient duplicate removal.",
  },
  {
    slug: "text-reverser",
    title: "Text Reverser",
    description: "Reverse text, words, or letters",
    category: "text-tool",
    icon: "ArrowLeftRight",
    keywords: [
      "text reverser",
      "reverse text",
      "backwards text",
      "flip text",
      "mirror text",
      "reverse words",
      "reverse letters",
    ],
    longDescription:
      "Reverse text, words, or individual letters. Perfect for fun, puzzles, and text manipulation. Reverse entire text, reverse word order, or reverse each word individually.",
  },
  {
    slug: "morse-code",
    title: "Morse Code Translator",
    description: "Convert text to Morse code and vice versa",
    category: "text-tool",
    icon: "Radio",
    keywords: [
      "morse code translator",
      "morse code converter",
      "text to morse",
      "morse to text",
      "morse code decoder",
      "morse code encoder",
    ],
    longDescription:
      "Convert text to Morse code and Morse code to text. Perfect for learning Morse code, communication, and educational purposes. Support for international Morse code standard.",
  },
  {
    slug: "character-frequency",
    title: "Character Frequency Counter",
    description: "Count character frequency in text",
    category: "text-tool",
    icon: "BarChart",
    keywords: [
      "character frequency",
      "letter frequency",
      "character count",
      "frequency analysis",
      "text analysis",
      "character statistics",
    ],
    longDescription:
      "Analyze character frequency in text. Perfect for cryptography, text analysis, and data science. Get detailed statistics about character distribution in your text.",
  },
  {
    slug: "html-encoder",
    title: "HTML Encoder/Decoder",
    description: "Encode and decode HTML entities",
    category: "text-tool",
    icon: "Code",
    keywords: [
      "html encoder",
      "html decoder",
      "html entities",
      "encode html",
      "decode html",
      "html escape",
      "html unescape",
    ],
    longDescription:
      "Encode and decode HTML entities. Perfect for web developers working with HTML content. Convert special characters to HTML entities and vice versa.",
  },
  {
    slug: "css-minifier",
    title: "CSS Minifier",
    description: "Minify and compress CSS code",
    category: "text-tool",
    icon: "FileCode",
    keywords: ["css minifier", "minify css", "compress css", "css compressor", "css optimizer", "reduce css size"],
    longDescription:
      "Minify and compress CSS code to reduce file size. Perfect for web developers optimizing website performance. Remove whitespace, comments, and unnecessary characters from CSS.",
  },
  {
    slug: "sql-formatter",
    title: "SQL Formatter",
    description: "Format and beautify SQL queries",
    category: "text-tool",
    icon: "Database",
    keywords: ["sql formatter", "format sql", "sql beautifier", "sql pretty print", "sql parser", "format sql query"],
    longDescription:
      "Format and beautify SQL queries. Perfect for database developers and administrators. Make SQL queries readable with proper indentation and formatting.",
  },
  {
    slug: "rot13-cipher",
    title: "ROT13 Cipher",
    description: "Encode and decode ROT13 cipher",
    category: "text-tool",
    icon: "Shield",
    keywords: ["rot13", "rot13 cipher", "rot13 encoder", "rot13 decoder", "caesar cipher", "text encryption"],
    longDescription:
      "Encode and decode text using ROT13 cipher. Perfect for simple text obfuscation, puzzles, and learning about ciphers. ROT13 is a simple letter substitution cipher.",
  },
  {
    slug: "caesar-cipher",
    title: "Caesar Cipher",
    description: "Encode and decode Caesar cipher with custom shift",
    category: "text-tool",
    icon: "Lock",
    keywords: [
      "caesar cipher",
      "caesar shift",
      "shift cipher",
      "caesar encoder",
      "caesar decoder",
      "substitution cipher",
    ],
    longDescription:
      "Encode and decode text using Caesar cipher with customizable shift value. Perfect for learning cryptography, puzzles, and simple text encryption. Classic substitution cipher.",
  },
  {
    slug: "jwt-decoder",
    title: "JWT Decoder",
    description: "Decode and verify JSON Web Tokens",
    category: "text-tool",
    icon: "KeyRound",
    keywords: [
      "jwt decoder",
      "json web token decoder",
      "jwt parser",
      "decode jwt",
      "jwt validator",
      "jwt debugger",
      "jwt token decoder",
    ],
    longDescription:
      "Decode and inspect JSON Web Tokens (JWT). View header, payload, and signature information. Perfect for developers debugging authentication and authorization. Validate JWT structure and expiration.",
  },
  {
    slug: "keyword-density-checker",
    title: "Keyword Density Checker",
    description: "Analyze keyword density in text",
    category: "text-tool",
    icon: "Target",
    keywords: [
      "keyword density checker",
      "keyword density",
      "seo keyword analyzer",
      "keyword frequency",
      "keyword counter",
      "seo analyzer",
      "keyword tool",
    ],
    longDescription:
      "Analyze keyword density and frequency in your content. Perfect for SEO optimization, content writing, and ensuring proper keyword usage. Get detailed statistics on word frequency and density percentages.",
  },

  // Utilities
  {
    slug: "stopwatch",
    title: "Stopwatch",
    description: "Precise stopwatch with lap times",
    category: "utility",
    icon: "Timer",
    keywords: ["stopwatch", "timer", "lap timer", "chronometer", "time tracker", "online stopwatch"],
    longDescription:
      "Precise online stopwatch with lap time tracking. Perfect for sports, workouts, cooking, and time tracking. Record multiple lap times and track elapsed time accurately.",
  },
  {
    slug: "countdown-timer",
    title: "Countdown Timer",
    description: "Set countdown timers with alerts",
    category: "utility",
    icon: "Clock",
    keywords: ["countdown timer", "timer", "countdown clock", "online timer", "alarm timer", "kitchen timer"],
    longDescription:
      "Set countdown timers with customizable alerts. Perfect for cooking, workouts, meetings, and time management. Get notified when time is up with sound alerts.",
  },
  {
    slug: "pomodoro-timer",
    title: "Pomodoro Timer",
    description: "Productivity timer with work/break intervals",
    category: "utility",
    icon: "Clock",
    keywords: ["pomodoro timer", "productivity timer", "focus timer", "work timer", "study timer", "time management"],
    longDescription:
      "Boost productivity with the Pomodoro Technique. Work in focused 25-minute intervals with short breaks. Perfect for studying, working, and improving time management.",
  },
  {
    slug: "image-compressor",
    title: "Image Compressor",
    description: "Compress images to reduce file size",
    category: "utility",
    icon: "ImageDown",
    keywords: [
      "image compressor",
      "compress image",
      "reduce image size",
      "image optimizer",
      "compress jpg",
      "compress png",
      "image size reducer",
      "optimize images",
    ],
    longDescription:
      "Compress images to reduce file size without losing quality. Support for JPG, PNG, and WebP formats. Perfect for optimizing images for websites, social media, and email. Fast and secure image compression.",
  },
  {
    slug: "image-resizer",
    title: "Image Resizer",
    description: "Resize images to custom dimensions",
    category: "utility",
    icon: "Maximize2",
    keywords: [
      "image resizer",
      "resize image",
      "image dimensions",
      "scale image",
      "crop image",
      "image size changer",
      "resize photo",
      "image scaler",
    ],
    longDescription:
      "Resize images to custom dimensions instantly. Maintain aspect ratio or set custom width and height. Perfect for social media, websites, and profile pictures. Support for JPG, PNG, and WebP formats.",
  },
  {
    slug: "pdf-merger",
    title: "PDF Merger",
    description: "Merge multiple PDF files into one",
    category: "utility",
    icon: "FilePlus",
    keywords: [
      "pdf merger",
      "merge pdf",
      "combine pdf",
      "join pdf files",
      "pdf combiner",
      "merge pdf online",
      "combine pdf files",
      "pdf joiner",
    ],
    longDescription:
      "Merge multiple PDF files into a single document. Upload PDFs, arrange them in order, and combine them instantly. Perfect for organizing documents, creating reports, and consolidating files. Fast and secure PDF merging.",
  },
  {
    slug: "pdf-splitter",
    title: "PDF Splitter",
    description: "Split PDF into separate pages or ranges",
    category: "utility",
    icon: "FileMinus",
    keywords: [
      "pdf splitter",
      "split pdf",
      "extract pdf pages",
      "pdf page extractor",
      "separate pdf pages",
      "split pdf online",
      "pdf divider",
    ],
    longDescription:
      "Split PDF files into separate pages or extract specific page ranges. Perfect for extracting important pages, dividing large documents, and organizing PDF content. Fast and secure PDF splitting.",
  },
  {
    slug: "date-calculator",
    title: "Date Calculator",
    description: "Calculate date differences and add/subtract days",
    category: "utility",
    icon: "CalendarDays",
    keywords: [
      "date calculator",
      "date difference calculator",
      "days between dates",
      "add days to date",
      "subtract days from date",
      "date math calculator",
      "date counter",
    ],
    longDescription:
      "Calculate the difference between two dates or add/subtract days from a date. Perfect for project planning, event countdown, and date calculations. Get results in years, months, weeks, and days.",
  },
  {
    slug: "business-days-calculator",
    title: "Business Days Calculator",
    description: "Calculate business days between dates",
    category: "utility",
    icon: "Briefcase",
    keywords: [
      "business days calculator",
      "working days calculator",
      "weekday calculator",
      "business day counter",
      "workday calculator",
      "exclude weekends calculator",
    ],
    longDescription:
      "Calculate business days between two dates, excluding weekends and holidays. Perfect for project management, delivery estimates, and business planning. Customize holidays for accurate calculations.",
  },
  {
    slug: "world-clock",
    title: "World Clock",
    description: "View current time in multiple time zones",
    category: "utility",
    icon: "Globe",
    keywords: [
      "world clock",
      "time zones",
      "current time worldwide",
      "international time",
      "global clock",
      "time zone clock",
      "world time zones",
    ],
    longDescription:
      "View current time in multiple time zones simultaneously. Perfect for international business, remote teams, and travel planning. Add your favorite cities for quick time zone reference.",
  },
]

export const categories = [
  { id: "all", label: "All Tools", icon: "Grid" },
  { id: "calculator", label: "Calculators", icon: "Calculator" },
  { id: "converter", label: "Converters", icon: "ArrowLeftRight" },
  { id: "generator", label: "Generators", icon: "Sparkles" },
  { id: "text-tool", label: "Text Tools", icon: "Type" },
  { id: "utility", label: "Utilities", icon: "Wrench" },
]
